FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential meson libva-dev pkg-config cmake

COPY . /repo
WORKDIR /repo/build
RUN meson ..
RUN ninja
